<a href="https://colab.research.google.com/github/samrachaana/AI-and-machine-learning/blob/main/2358481_ShreeyaLama_Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Workshop - 0**

In [1]:
import sys

# First, check python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
  print("Hello world!")
  print(f"Python Version: {sys.version}")
else:
  print("Please use Python 3.6 or higher!")



Hello world!
Python Version: 3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0]


In [ ]:
age = 20
pi = 3.14
temp = -5.5
print("datatype of varaible age= ", type(age))
print("datatype of varaible pi= ", type(pi))
print("datatype of varaible temp= ", type(temp))

datatype of varaible age=  <class 'int'>
datatype of varaible pi=  <class 'float'>
datatype of varaible temp=  <class 'float'>


In [2]:
name = "Shreeya"
greeting = 'Namaste'
address = "Kathmandu"
print("datatype of varaible name= ", type(name))
print("datatype of varaible greeting= ", type(greeting))
print("datatype of varaible address= ", type(address))

# slice an element
print("The first letter of name= ", name[0])
print("The last letter of name= ", name[-1])

# slice a range of elements
print("The first letter to sixth letter of name= ", name[0:6])
print("The first two letters of name= ", name[:2])
print("Substring of name from the fifth letter= ", name[4:])


datatype of varaible name=  <class 'str'>
datatype of varaible greeting=  <class 'str'>
datatype of varaible address=  <class 'str'>
The first letter of name=  S
The last letter of name=  a
The first letter to sixth letter of name=  Shreey
The first two letters of name=  Sh
Substring of name from the fifth letter=  eya


In [3]:
#list -can contain mixed datatypes
a_list = [1,2,3,4]
mixed_list = [15,"Hi", False]
#List is mutable
mixed_list[0]=  True
mixed_list

[True, 'Hi', False]

In [6]:
#1
fruits = ('apple', 'orange', 'strawberry', 'blueberry')

# Convert tuple to list
fruits_list = list(fruits)

# Modify the list
fruits_list[0] = 'banana'

# Convert back to tuple
fruits = tuple(fruits_list)

print(fruits)

#2
fruits = ('apple', 'orange', 'strawberry', 'blueberry')

# Create a new tuple
fruits = ('banana',) + fruits[1:]

print(fruits)



('banana', 'orange', 'strawberry', 'blueberry')
('banana', 'orange', 'strawberry', 'blueberry')


In [7]:
# dictionary
me = {"name":"Shreeya", 'age':20}
print("Keys",list(me.keys()))
print("Values:",list(me.values()))

Keys ['name', 'age']
Values: ['Shreeya', 20]


In [ ]:
my_age=me.get('age')
my_age

20

In [ ]:
# set
unique = {21,21,32,35,23,54,23,32,5,3423,1,21}
print(unique)

{32, 1, 35, 5, 21, 54, 23, 3423}


In [ ]:
#boolean
is_student = True
has_license = False
print(is_student)
print(has_license)

True
False


In [ ]:
result  = None
result

In [ ]:
# logical statements
x = 3
if(x>0):
  print("x is positive")
elif (x<0):
  print("positive number")
else: # x==0
  print("0")

x is positive


In [ ]:
a = True
b= False
if not a:
  print("a is false")
if a and not b:
  print("a is true and b is false")

a is true and b is false


In [ ]:
#for loop
fruits = ['apple','orange','strawberry','blueberry']
print("loop1")
for fruit in fruits:
  if fruit == 'orange':
    continue
  else:
    print(fruit)
print("loop2")
for fruit in fruits:
  print(fruit)
  if fruit == 'strawberry':
    break



loop1
apple
strawberry
blueberry
loop2
apple
orange
strawberry


In [ ]:
fruits.append("cherry")
fruits

['apple', 'orange', 'strawberry', 'blueberry', 'cherry']

In [ ]:
fruit = fruits[2].upper()
fruit

'STRAWBERRY'

In [ ]:
#functions

def add_binary(a,b):
  binary_sum = bin(a+b)[2:]
  return binary_sum

add_binary(4,7)

'1011'

# **Exercises**

#1.Exercise on Functions:

Task - 1:

Create a Python program that converts between different units of measurement.
*   The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
*   Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and return value.
*   Conversion Options:
1. Length:
- Convert meters (m) to feet (ft).
- Convert feet (ft) to meters (m).
2. Weight:
- Convert kilograms (kg) to pounds (lbs).
- Convert pounds (lbs) to kilograms (kg).
3. Volume:
- Convert liters (L) to gallons (gal).
- Convert gallons (gal) to liters (L).


In [ ]:
def get_choice():
    """This function prompts the user to choose the type of conversion they want.
    Returns:
    str: The choice of conversion type.
    """

    conversion_options = {
        "1": ("m_to_ft", "Length: meters (m) to feet (ft)", "m", "ft"),
        "2": ("ft_to_m", "Length: feet (ft) to meters (m)", "ft", "m"),
        "3": ("kg_to_pounds", "Weight: kilograms (kg) to pounds (lbs)", "kg", "lbs"),
        "4": ("pounds_to_kg", "Weight: pounds (lbs) to kilograms (kg)", "lbs", "kg"),
        "5": ("L_to_gal", "Volume: liters (L) to gallons (gal)", "L", "gal"),
        "6": ("gal_to_L", "Volume: gallons (gal) to liters (L)", "gal", "L")
    }

    print("Select a conversion option:")
    for key, value in conversion_options.items():
        print(f"{key}. {value[1]}")

    choice = input("Enter the number of the conversion you want: ").strip()
    return conversion_options.get(choice, None)

def convert(value, conv_choice):
    """
    Converts the given value based on the conversion type.

    Parameters:
    conversion_functions (dict): A dictionary containing conversion functions.
    value (float): The value to be converted.
    conv_choice (str): The conversion type choice

    Returns:
    float: The converted value.
    """
    conversion_functions = {
        "m_to_ft": lambda v: v * 3.281,
        "ft_to_m": lambda v: v / 3.281,
        "kg_to_pounds": lambda v: v * 2.20462,
        "pounds_to_kg": lambda v: v * 0.453592,
        "L_to_gal": lambda v: v * 0.264172,
        "gal_to_L": lambda v: v * 3.78541
    }

    return conversion_functions.get(conv_choice, lambda v: None)(value)

def main():
    while True:
        conversion_choice = get_choice()

        if not conversion_choice:
            print("Invalid choice. Please select a valid option.")
            continue

        conv_type, desc, from_unit, to_unit = conversion_choice
        print(f"You have selected: {desc}")

        try:
            value = float(input(f"Enter the value in {from_unit}: "))
            converted_value = convert(value, conv_type)

            if converted_value is not None:
                print(f"{value} {from_unit} is equal to {converted_value:.4f} {to_unit}")
            else:
                print("Conversion error. Please try again.")

        except ValueError:
            print("Invalid input. Please enter a valid number.")

        another = input("Do you want to perform another conversion? (yes/no): ").strip().lower()
        if another != "yes":
            print("End of program!")
            break

if __name__ == "__main__":
    main()


Select a conversion option:
1. Length: meters (m) to feet (ft)
2. Length: feet (ft) to meters (m)
3. Weight: kilograms (kg) to pounds (lbs)
4. Weight: pounds (lbs) to kilograms (kg)
5. Volume: liters (L) to gallons (gal)
6. Volume: gallons (gal) to liters (L)
Enter the number of the conversion you want: 6
You have selected: Volume: gallons (gal) to liters (L)
Enter the value in gal: 4
4.0 gal is equal to 15.1416 L
Do you want to perform another conversion? (yes/no): n
End of program!


Task - 2:

Create a Python program that performs various mathematical operations on a list of numbers.
*   The program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum of the numbers)
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
*   Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, minimum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def find_sum(nums):
  """
  Calculates the sum of a list of numbers

  Parameters:
  nums(list of float): list of float numbers

  Returns
  float: sum of numbers

  """
  return sum(nums)

def average(nums):
  """
    Calculates the average of a list of numbers.

    Parameters:
    nums(list of float: list of float numbers.

    Returns:
    float: average of the numbers.
    """
  return sum(nums)/len(nums)

def find_max(nums):
  """
    Finds the maximum value in a list of numbers.

    Parameters:
    nums(list of float: list of float numbers.

    Returns:
    float: maximum number.
    """
  return max(nums)

def find_min(nums):
  """
    Finds the minimum value in a list of numbers.

    Parameters:
    nums(list of float): list of float numbers.

    Returns:
    float: minimum number.
    """
  return min(nums)

def get_nums():
  """
  Prompts user to enter a list of numbers
  Returns:
  list of float: the list of numbers entered by the user

  """
  while True:
    try:
      numbers = list(map(float,input("Enter numbers separated by spaces: ").split()))
      if not numbers:
        print("Error: The list cannot be empty. Please enter at leeast one number")
        continue
      return numbers
    except ValueError:
      print("Error: Invalid input. Please enter numbers separated by spaces.")


def main():
  operations = {
      "1": ("Sum", sum),
      "2": ("Average", average),
      "3": ("Maximum", find_max),
      "4": ("Minimum", find_min)
  }
  while True:
    print("\nChoose a mathematical operations: ")
    for key,(name,_) in operations.items():
      print(f"{key}. {name}")

    choice = input("Enter the numbers of the operation you want to perform:").strip()

    if choice not in operations:
      print("Invalid choice. Please select a valid option.")
      continue

    operation_name, operation_func = operations[choice]
    print(f"You have selected: {operation_name}")

    num = get_nums()
    res = operation_func(num)

    if res is not None:
      print(f"Result:{res}")
    else:
      print("Error")

    again = input("Do you want to perform another operation? (yes/no): ").strip().lower()
    if again != "yes":
      print("End of program!")
      break

if __name__ == "__main__":
  main()



Choose a mathematical operations: 
1. Sum
2. Average
3. Maximum
4. Minimum
Enter the numbers of the operation you want to perform:6
Invalid choice. Please select a valid option.

Choose a mathematical operations: 
1. Sum
2. Average
3. Maximum
4. Minimum
Enter the numbers of the operation you want to perform:2
You have selected: Average
Enter numbers separated by spaces: 
Error: The list cannot be empty. Please enter at leeast one number
Enter numbers separated by spaces: 3 4 3 2 4 2
Result:3.0
Do you want to perform another operation? (yes/no): no
End of program!


## Exercise on List Manipulation:

1. Extract Every Other Element:

  Write a Python function that extracts every other element from a list, starting from the first element.

  Requirements:
- Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
- Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].


In [ ]:
def extract(lst):
  """
  Extracts every other elemet from a list, starting from the first element.

  Parameters:
  lst (list): The input list

  Returns:
  list: a new list containing every other element from the original list
  """
  return lst[::2]

lst =[1,2,3,4,5,6,7,8]
new_lst =[]
res = extract(lst)
print("Original list:", lst)
print("The new list with every other element: ", res)

Original list: [1, 2, 3, 4, 5, 6, 7, 8]
The new list with every other element:  [1, 3, 5, 7]


2. Slice a Sublist:

  Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

  Requirements:
- Define a function get sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive).
- Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
  """
  Returns a sublist from a given list, starting from a specified index and ending at another specified index.

  Parameters:
  lst (list): The input list
  start (int): The starting index
  end (int): The ending index

  Returns:
  list: The sublist from start to end (inclusive)

  """

  return lst[start:end+1]

lst = [1, 2, 3, 4, 5, 6]
start = 2
end = 4
res = get_sublist(lst, start, end)
print("Original list:", lst)
print("The sublist from the specified start to end is: ", res)

Original list: [1, 2, 3, 4, 5, 6]
The sublist from the specified start to end is:  [3, 4, 5]


3. Reverse a List Using Slicing:

  Write a Python function that reverses a list using slicing.

  Requirements:
- Define a function reverse list(lst) that takes a list lst and returns a reversed list using slicing.
- Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse(lst):
  return lst[::-1]

lst = [1, 2, 3, 4, 5, 6]
res = reverse(lst)
print("Original list:", lst)
print("The reversed list is: ", res)

Original list: [1, 2, 3, 4, 5, 6]
The reversed list is:  [6, 5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

  Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

  Requirements:
- Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
- Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove(lst):
  return lst[1:-1]

lst = [1, 2, 3, 4, 5, 6, 7, 8]
res = remove(lst)
print("Original list:", lst)
print("The sublist without the first and last elements is: ", res)

Original list: [1, 2, 3, 4, 5, 6, 7, 8]
The sublist without the first and last elements is:  [2, 3, 4, 5, 6, 7]


5. Get the First n Elements:

  Write a Python function that extracts the first n elements from a list.

  Requirements:
- Define a function get first n(lst, n) that takes a list lst and an integer n as input and returns the first n elements of the list using slicing.
- Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
  return lst[:n]

lst = [1, 2, 3, 4, 5, 6, 7, 8]
n = 4
res = get_first_n(lst, n)
print("Original list:", lst)
print("The first", n, "elements of the list are: ", res)

Original list: [1, 2, 3, 4, 5, 6, 7, 8]
The first 4 elements of the list are:  [1, 2, 3, 4]


6. Extract Elements from the End:

  Write a Python function that extracts the last n elements of a list using slicing.

  Requirements:
- Define a function get last n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.
- Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
  return lst[-n:]

lst = [1, 2, 3, 4, 5, 6, 7, 8]
n = 4
res = get_last_n(lst, n)
print("Original list:", lst)
print("The last", n, "elements of the list are: ", res)

Original list: [1, 2, 3, 4, 5, 6, 7, 8]
The last 4 elements of the list are:  [5, 6, 7, 8]


7. Extract Elements in Reverse Order:

  Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

  Requirements:
- Define a function reverse skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.
- Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
  return lst[-2::-2]

lst = [1, 2, 3, 4, 5, 6, 7, 8]
res = reverse_skip(lst)
print("Original list:", lst)
print("Every other element in reverse order: ",res)

Original list: [1, 2, 3, 4, 5, 6, 7, 8]
Every other element in reverse order:  [7, 5, 3, 1]


## Exercise on Nested List:

1. Flatten a Nested List:

  Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

  Requirements:
- Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.
- Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
  flattened_lst = []
  for sublist in lst:
    for item in sublist:
      flattened_lst.append(item)
  return flattened_lst

lst = [1, 2], [3, 4], [5, 6], [7, 8]
print("Original list:", lst)
flattened_lst = flatten(lst)
print("Flattened list:", flattened_lst)

Original list: ([1, 2], [3, 4], [5, 6], [7, 8])
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


2. Accessing Nested List Elements:

  Write a Python function that extracts a specific element from a nested list given its indices.

  Requirements:
- Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.
- Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1, 2], the output should be 6.

In [ ]:
def access_nested_element(lst,indices):
  elemt = lst[indices[0]][indices[1]]
  return elemt

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 1]
res = access_nested_element(lst, indices)
print("Original list:", lst)
print("The element at the specified indices is: ", res)

Original list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
The element at the specified indices is:  5


3. Sum of All Elements in a Nested List:

  Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

  Requirements:
- Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements.
- Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
  sum = 0
  for item in lst:
    if isinstance(item, list):
      sum += sum_nested(item)
    else:
      sum += item
  return sum

lst = [[1, 2, 3], [4, 5,[10,11], 6], [7, 8, 9]]
print("Original list:", lst)
res = sum_nested(lst)
print("Sum of all the elements in the nested list = ", res)

Original list: [[1, 2, 3], [4, 5, [10, 11], 6], [7, 8, 9]]
Sum of all the elements in the nested list =  66


4. Remove Specific Element from a Nested List:
  
  Write a Python function that removes all occurrences of a specific element from a nested list.

  Requirements:
- Define a function remove element(lst, elem) that removes elem from lst and returns the modified list.
- Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
  for sublist in lst:
    while elem in sublist:
      sublist.remove(elem)
  return lst
lst = [[1, 2, 3], [4, 5,[10,11], 6], [7, 8]]
elem = 5
print("Original list:", lst)
res = remove_element(lst, elem)
print("The modified list after removing the element is: ", res)

Original list: [[1, 2, 3], [4, 5, [10, 11], 6], [7, 8]]
The modified list after removing the element is:  [[1, 2, 3], [4, [10, 11], 6], [7, 8]]


5. Find the Maximum Element in a Nested List:

  Write a Python function that finds the maximum element in a nested list (regardless of depth).

  Requirements:
- Define a function find max(lst) that takes a nested list lst and returns the maximum element.
- Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
  max_val = float('-inf')
  for item in lst:
    if isinstance(item, list):
      max_val = max(max_val, find_max(item))
    else:
      max_val = max(max_val, item)
  return max_val
lst = [[1, 2, 3], [4, 5,[10,11], 6], [7, 8, 9]]
print("Original list:", lst)
max_value = find_max(lst)
print("The maximum element in the nested list is:",max_value)


Original list: [[1, 2, 3], [4, 5, [10, 11], 6], [7, 8, 9]]
The maximum element in the nested list is: 11


6. Count Occurrences of an Element in a Nested List:

  Write a Python function that counts how many times a specific element appears in a nested list.

  Requirements:
- Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.
- Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should be 3.

In [ ]:
def count_occurrences(lst, elem):
  count = 0
  for item in lst:
    if isinstance(item,list):
      count += count_occurrences(item, elem)
    elif item == elem:
      count += 1
  return count

lst = [[1, 7, 3], [4, 5,[10,7], 6], [7, 7, 9]]
print("Original list:", lst)
elem = 7
res = count_occurrences(lst,elem)
print(f"Number of occurrences of {elem} in the nested list is: ", res)

Original list: [[1, 7, 3], [4, 5, [10, 7], 6], [7, 7, 9]]
Number of occurrences of 7 in the nested list is:  4


7. Flatten a List of Lists of Lists:

  Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

  Requirements:
- Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list.
- Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
  flattened_lst = []
  for item in lst:
    if isinstance(item, list):
      flattened_lst.extend(deep_flatten(item))
    else:
      flattened_lst.append(item)
  return flattened_lst

lst = [[1, 7, 3], [4, 5,[10,17], 6], [7, 71, 9]]
print("Original list:", lst)
flattened_lst = deep_flatten(lst)
print("Flattened list:", flattened_lst)

Original list: [[1, 7, 3], [4, 5, [10, 17], 6], [7, 71, 9]]
Flattened list: [1, 7, 3, 4, 5, 10, 17, 6, 7, 71, 9]


8. Nested List Average:

  Write a Python function that calculates the average of all elements in a nested list.

  Requirements:
- Define a function average nested(lst) that takes a nested list lst and returns the average of all the elements.
- Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def avg_nested(lst):
  flattened_lst = deep_flatten(lst)
  total = sum(flattened_lst)
  return total/len(flattened_lst)
lst = [[1, 2, 3], [4, 5,[10,11], 6], [7, 8, 9]]
print("Original list:", lst)
res = avg_nested(lst)
print("The average of all the elements in the nested list is: ", res)

Original list: [[1, 2, 3], [4, 5, [10, 11], 6], [7, 8, 9]]
The average of all the elements in the nested list is:  6.0


## Basic Vector and Matrix Operation with Numpy
### Problem - 1: Array Creation:


In [ ]:
import numpy as np

1. Initialize an empty array with size 2X2.

In [ ]:
empty_array = np.empty((2,2))
print("Empty Array: \n",empty_array)

Empty Array: 
 [[2.42131934e-316 0.00000000e+000]
 [6.83747917e-310 4.89665695e-317]]


2. Initialize an all one array with size 4X2.

In [ ]:
all_one_array = np.ones((4,2))
print("All One Array: \n",all_one_array)

All One Array: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
new_array = np.full((6,2),6.06, dtype = float)
print("New Array: \n",new_array)

New Array: 
 [[6.06 6.06]
 [6.06 6.06]
 [6.06 6.06]
 [6.06 6.06]
 [6.06 6.06]
 [6.06 6.06]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
new_zeros_array = np.zeros_like(new_array)
print("New Array of zeros: \n",new_zeros_array)

New Array of zeros: 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
print(" New Array of ones: \n",np.ones_like(new_array))

 New Array of ones: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1,2,3,4]
new_arr = np.array(new_list)
print("Numpy Array: \n",new_arr)
print("Type: ", type(new_arr))

Numpy Array: 
 [1 2 3 4]
Type:  <class 'numpy.ndarray'>


### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
print("Array with values ranging from 10 to 49: \n",np.arange(10,50))

Array with values ranging from 10 to 49: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}

In [ ]:
array = np.arange(9)
matrix = np.reshape(array,(3,3))
print("3X3 matrix with values ranging from 0 to 8: \n",matrix)

3X3 matrix with values ranging from 0 to 8: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
print("3X3 identity matrix: \n", np.eye(3,dtype=int))

3X3 identity matrix: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
random_arr = np.random.random(30)
print(f"Random array of size 30:\n{random_arr}")
mean = np.mean(random_arr)
print("\nMean:",mean)

Random array of size 30:
[0.59878812 0.19924577 0.57795392 0.78123239 0.06632669 0.2559697
 0.1606254  0.24422971 0.67470321 0.71579882 0.32944193 0.47086627
 0.81900753 0.37570703 0.22378909 0.58017557 0.98662907 0.59942184
 0.64134824 0.70411209 0.41265326 0.72510883 0.48383428 0.95361006
 0.22954887 0.04641122 0.86857775 0.38464091 0.37904969 0.1712956 ]

Mean: 0.4886700954266602


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
array = np.random.random((10, 10))
print(f"10X10 array with random values:\n{array}")
print(f"\nMinimum value: {np.min(array)}")
print(f"\nMaximum value: {np.max(array)}")

10X10 array with random values:
[[0.47798266 0.19895343 0.06450715 0.53491571 0.52783316 0.39132629
  0.16409748 0.60152279 0.92867195 0.94524131]
 [0.86119741 0.19482841 0.69911464 0.39548102 0.30366052 0.79330528
  0.35664277 0.53044776 0.2095761  0.26757601]
 [0.22503256 0.19568052 0.47414027 0.74763959 0.65181485 0.83400466
  0.00398966 0.05710007 0.1925141  0.4979999 ]
 [0.35718206 0.92101655 0.3695884  0.80762022 0.9680993  0.7913756
  0.98645839 0.61841783 0.37469439 0.73347547]
 [0.65638339 0.15192768 0.39525403 0.41883402 0.40148482 0.35722166
  0.60516661 0.91700767 0.97542258 0.84240067]
 [0.24252401 0.04629901 0.84040252 0.23822784 0.87132902 0.42367093
  0.85139886 0.11450062 0.74511647 0.81760846]
 [0.70346154 0.21095422 0.47252491 0.71178441 0.92276795 0.17185045
  0.42388629 0.14470812 0.85051168 0.49028672]
 [0.11080717 0.16587911 0.66431238 0.10586252 0.10684352 0.97399632
  0.43217194 0.91189993 0.144332   0.94932819]
 [0.37069194 0.24321932 0.61314075 0.92701168 0.7

6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
zero_arr = np.zeros(10, dtype=int)
zero_arr[4] = 1
print("Array:",zero_arr)

Array: [0 0 0 0 1 0 0 0 0 0]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr = [1,2,0,0,4,0]
reversed_arr = arr[::-1]
print("Original array:",arr)
print("Reversed array:",reversed_arr)

Original array: [1, 2, 0, 0, 4, 0]
Reversed array: [0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
arr = np.ones((5,5), dtype=int)
arr[1:-1,1:-1] = 0
print("2d array with 1 on border and 0 inside:\n",arr)

2d array with 1 on border and 0 inside:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
arr = np.zeros((8,8), dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print("Checkerboard pattern:\n",arr)

Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:


1. Add the two array.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Addition:")
add_xy = np.add(x, y)
print(f"{x}\n+\n{y} = ")
print(add_xy)

print("")
add_vw = np.add(v, w)
print(f"{v} + {w} = {add_vw}")



Addition:
[[1 2]
 [3 5]]
+
[[5 6]
 [7 8]] = 
[[ 6  8]
 [10 13]]

[ 9 10] + [11 12] = [20 22]


2. Subtract the two array.

In [ ]:
print("Subtraction")
subtract_xy = np.subtract(x, y)
print(f"{x}\n-\n{y} = ")
print(subtract_xy)

print("")
subtract_vw = np.subtract(v, w)
print(f"{v} - {w} = {subtract_vw}")

Subtraction
[[1 2]
 [3 5]]
-
[[5 6]
 [7 8]] = 
[[-4 -4]
 [-4 -3]]

[ 9 10] - [11 12] = [-2 -2]


3. Multiply the array with any integers of your choice.

In [ ]:
print("Multiplication")
multiply_x = np.dot(x,6)
print(f"6 . {x} = \n{multiply_x}")

Multiplication
6 . [[1 2]
 [3 5]] = 
[[ 6 12]
 [18 30]]


4. Find the square of each element of the array.

In [ ]:
print("Original array:",y)
print("Array with quared elements", y**2)

Original array: [[5 6]
 [7 8]]
Array with quared elements [[25 36]
 [49 64]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
print("Dot Products:")
dot_prod_vw = np.dot(v, w)
print("\nv(and)w:", dot_prod_vw)
dot_prod_xv = np.dot(x, v)
print("\nx(and)v:", dot_prod_xv)
dot_prod_xy = np.dot(x, y)
print("\nx(and)y:", dot_prod_xy)

Dot Products:

v(and)w: 219

x(and)v: [29 77]

x(and)y: [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
print("Concatenating x(and)y along row:")
concatenate_xy = np.concatenate((x, y), axis=0)
print(concatenate_xy)

print("\nConcatenating v(and)w along column:")
concatenate_vw = np.concatenate_column = np.vstack((v, w)).T
print(concatenate_vw)

Concatenating x(and)y along row:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenating v(and)w along column:
[[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
print("\nConcatenating x(and)v:")
concatenate_xv = np.concatenate((x, v), axis=0)
print(concatenate_xv)


Concatenating x(and)v:


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

The arrays x and v used to perform the concatenation hace different dimensions.

Thus, the concatenation is not possible.

### Problem - 4: Matrix Operations:
- For the following arrays:

  A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

  Prove following with Numpy:
  1. Prove A.A−1 = I.
  2. Prove AB ̸= BA.
  3. Prove(AB)T =BTAT.

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [ ]:
from numpy import linalg

inverse_A = np.linalg.inv(A)
result_1 = np.dot(A, inverse_A)
print(f"1. A.A−1:\n{np.round(result_1)}")

dot_product_AB = np.dot(A, B)
dot_product_BA = np.dot(B, A)

check = np.array_equal(dot_product_AB, dot_product_BA)
print("\n")
if check == True:
  print("2. AB = BA")
else:
  print("2. AB != BA")

transpose_A = np.transpose(A)
transpose_B = np.transpose(B)

product_BTAT = np.dot(transpose_B, transpose_A)
transpose_AB = np.transpose(dot_product_AB)

check1 = np.array_equal(transpose_AB, product_BTAT)
print("\n")
if check1 == True:
  print("3. (AB)T = BT.AT")
else:
  print("3. (AB)T != BT.AT")

1. A.A−1:
[[1. 0.]
 [0. 1.]]


2. AB != BA


3. (AB)T = BT.AT


- Solve the following system of Linear equation using Inverse Methods.

  2x − 3y + z = −1

  x − y + 2z = −3

  3x + y − z = 9

  {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

In [ ]:
print("Coefficient matrix A:")
print(A)
print("\nConstant matrix B:")
print(B)

Coefficient matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Constant matrix B:
[-1 -3  9]


In [ ]:
det_A = np.linalg.det(A)

cofactor_matrix = np.zeros_like(A, dtype=float)

for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        minor_matrix = np.delete(np.delete(A, i, axis=0), j, axis=1)
        cofactor_matrix[i, j] = ((-1) ** (i + j)) * np.linalg.det(minor_matrix)

adjugate_matrix = cofactor_matrix.T

# inverse of A
A_inv = adjugate_matrix / det_A

In [ ]:
X = np.dot(A_inv, B)
print("Solution using Inverse Methods:")
print(X)

Solution using Inverse Methods:
[ 2.  1. -2.]


- Now: solve the above equation using np.linalg.inv function. {Explore more about ”linalg” func- tion of Numpy}

In [ ]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution using np.linalg.inv function:")
print(X)

Solution using np.linalg.inv function:
[ 2.  1. -2.]


### Experiment: How Fast is Numpy?

1. Element-wise Addition:
- Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
- Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.


In [ ]:
import time

lst1 = [i for i in range(1,1000001)]
lst2 = [i for i in range(1000001,2000001)]

start_time = time.time()
result_time = [a+b for a,b in zip(lst1, lst2)]
end_time = time.time()
add_time = end_time - start_time
print(f"Time taken for element-wise addition: {add_time} seconds")

arr1 = np.array(lst1)
arr2 = np.array(lst2)

start_time = time.time()
result_array = arr1 + arr2
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken for element-wise addition using Numpy arrays: {array_time} seconds")

Time taken for element-wise addition: 0.10199308395385742 seconds
Time taken for element-wise addition using Numpy arrays: 0.004677772521972656 seconds


2. Element-wise Multiplication
- Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000. Measure and Print the time taken for this operation.
- Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
start_time = time.time()
result_lst = [a*b for a,b in zip(lst1, lst2)]
end_time = time.time()
multiplication_time = end_time - start_time
print(f"Time taken for element-wise multiplication: {multiplication_time} seconds")

array1 = np.array(lst1)
array2 = np.array(lst2)

start_time = time.time()
result_array = array1 * array2
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken for element-wise multiplication using Numpy arrays: {array_time} seconds")

Time taken for element-wise multiplication: 0.09686112403869629 seconds
Time taken for element-wise multiplication using Numpy arrays: 0.009573698043823242 seconds


3. Dot Product
- Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
- Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
start_time = time.time()
result_time = [a*b for a,b in zip(lst1, lst2)]
end_time = time.time()
dot_product_time = end_time - start_time
print(f"Time taken to compute the dot product: {dot_product_time} seconds")

array1 = np.array(lst1)
array2 = np.array(lst2)

start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken to compute the dot product using Numpy arrays: {array_time} seconds")

Time taken to compute the dot product: 0.10945296287536621 seconds
Time taken to compute the dot product using Numpy arrays: 0.001950979232788086 seconds


4. Matrix Multiplication
- Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
- Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [ ]:
N=1000

matrix1 = [[i + j for j in range(N)] for i in range(N)]
matrix2 = [[i - j for j in range(N)] for i in range(N)]

def mat_mul(A,B):
  result = [[0] *N for _ in range(N)]
  for i in range(N):
    for j in range(N):
      for k in range(N):
        result[i][j] += A[i][k] * B[k][j]
  return result

start_time = time.time()
result = mat_mul(matrix1, matrix2)
end_time = time.time()
mat_mul_time = end_time - start_time
print(f"Time taken for matrix multiplication: {mat_mul_time} seconds")

array1 = np.array(matrix1)
array2 = np.array(matrix2)

start_time = time.time()
result_numpy = np.dot(array1, array2)
end_time = time.time()
numpy_matmul_time = end_time - start_time
print(f"Time taken for matrix multiplication using Numpy arrays: {numpy_matmul_time:.6f} seconds")

Time taken for matrix multiplication: 187.64951491355896 seconds
Time taken for matrix multiplication using Numpy arrays: 2.182149 seconds
